---
#- name: Install Dependencies
#  block:
#    - name: Install Docker
#      include_role:
#        name: geerlingguy.docker
#      vars:
#        docker_package_state: latest
#  become: yes

- name: Start WireGuard
  block:
    - name: Start container
      community.docker.docker_container:
        name: wireguard
        image: lscr.io/linuxserver/wireguard:latest
        state: started
        pull: true
        restart_policy: unless-stopped
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Etc/UTC
          SERVERURL: "168.100.8.4"
          SERVERPORT: "51820"
          PEERS: "Oleg,Roma"
          PEERDNS: auto
          INTERNAL_SUBNET: 10.13.13.0
          ALLOWEDIPS: 0.0.0.0/0
          PERSISTENTKEEPALIVE_PEERS: ""
          LOG_CONFS: "true"
        ports:
          - "51820:51820/udp"
        volumes:
          - "/path/to/appdata/config:/config"
          - "/lib/modules:/lib/modules"
        sysctls:
          net.ipv4.conf.all.src_valid_mark: "1"
